language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install requests
# command to run tests
script: 
  - python test.py
  - a=1
  - echo "a is __${a}__ "
  - dsfsdafsdfsd
  - echo "a is __${a}__ "
